options:
  channel:
    type: string
    default: "latest/edge"
    description: |
      Snap channel from which to install the kubernetes-test snap.
  context:
    type: string
    default: ""
    description: |
      The context to use from the kubeconfig file.
