name: VSphere Integration Tests
on:
  pull_request:
  schedule:
  - cron: "0 1 * * 0"  # Run weekly at 1am on Sundays

jobs:
  call-inclusive-naming-check:
    name: Inclusive naming
    uses: canonical/inclusive-naming/.github/workflows/woke.yaml@7aa0f7a606f182bd03a7adb28e0d710216101ca5 # main
    with:
      fail-on-error: "true"

  lint-unit:
    name: Lint Unit
    uses: charmed-kubernetes/workflows/.github/workflows/lint-unit.yaml@6ee58c37d404effad4598ce7b523dbaf0cb99285 # main
    with:
      python: "['3.10', '3.12']"
    needs:
      - call-inclusive-naming-check

  charm-source:
    name: Kubernetes-E2E Source
    runs-on: ubuntu-latest
    outputs:
      channel: ${{ steps.charm.outputs.channel }}
    steps:
      - name: Pull-Request charm channel
        id: charm
        run: |
          set -euo pipefail
          CHANNEL=""
          SCHEDULE="${{ github.event.schedule || '' }}"
          if [ "${SCHEDULE}" = "0 1 * * 0" ]; then
            CHANNEL="latest/edge"
            echo "Using ${CHANNEL} channel for weekly schedule"
          fi

          if [ -z "${CHANNEL}" ]; then
            echo "Using empty channel for pull request"
          fi
          echo "channel=${CHANNEL}" >> $GITHUB_OUTPUT

  integration-test:
    name: Integration test with VMWare
    runs-on: self-hosted
    strategy:
      max-parallel: 1
      matrix:
        distribution: [canonical-kubernetes, charmed-kubernetes]
    needs:
      - lint-unit
      - charm-source
    env:
      # Set default values
      EXTRA_ARGS: "--basetemp=/home/ubuntu/pytest --kubernetes-distribution=${{ matrix.distribution }}"
    timeout-minutes: 90
    steps:
      - name: Check out code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Read charmcraft version file
        id: charmcraft
        run: echo "channel=$(cat .charmcraft-channel)" >> $GITHUB_OUTPUT

      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.10'

      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@ea90ed489690bf3b1c1fcca6ac5f9edab70aecb0 # main
        with:
          provider: vsphere
          juju-channel: "3/stable"
          charmcraft-channel: ${{ steps.charmcraft.outputs.channel }}
          credentials-yaml: ${{ secrets.CREDENTIALS_YAML }}
          clouds-yaml: ${{ secrets.CLOUDS_YAML }}
          bootstrap-constraints: "arch=amd64 cores=2 mem=4G"
          bootstrap-options: "${{ secrets.JAMMY_BOOTSTRAP_OPTIONS }} --model-default datastore=vsanDatastore --model-default primary-network=VLAN_2763"

      - if: ${{ needs.charm-source.outputs.channel }}
        name: Test from kubernetes-e2e channel=${{ needs.charm-source.outputs.channel }}
        run: |
          echo "EXTRA_ARGS=${EXTRA_ARGS} --kubernetes-e2e-channel=${{needs.charm-source.outputs.channel}}" >> $GITHUB_ENV

      - name: Run integration test
        run: tox -e integration -- ${EXTRA_ARGS}

      - name: Setup Debug Artifact Collection
        if: ${{ failure() }}
        run: mkdir tmp

      - name: Collect Juju Status
        if: ${{ failure() }}
        run: |
          juju status 2>&1 | tee tmp/juju-status.txt
          juju-crashdump -s -m controller -a debug-layer -a config -o tmp/
          mv juju-crashdump-* tmp/ | true
          mv $HOME/.local/state/charmcraft/log

      - name: Upload debug artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: test-run-artifacts
          path: tmp
